### ISSUE TITLE
找不到so

### ISSUE THREAD

**Issue by LxzBUG** [TestPlanB/SillyBoy#7]
我是直接把jniLibs的so删了 运行 然后手动放app外部私有目录里，点击一个按钮加载so
错误信息是ib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libxxxx.so"😂 我debug看了 传的文件是存在的

**Comment by TestPlanB** [comment]
可以用demo看一下有没有这个问题，需要确保外部私有目录能够被访问到
